GamesForU/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GamesForU.Data;
using GamesForU.Models;
using Microsoft.AspNetCore.Identity;
using QuestPDF.Fluent;

namespace GamesForU.Controllers
{
    public class HistoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public HistoryController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }
        private Task<IdentityUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }


        // GET: History
        public async Task<IActionResult> Index()
        {
            IdentityUser curruser = await GetCurrentUserAsync();
            if (curruser == null)
            {
                return NotFound();
            }
            bool isAdmin = await _userManager.IsInRoleAsync(curruser, "Admin");


            if (isAdmin)
            {
                var applicationDbContext = _context.GamesOrders.Include(g => g.Games).Include(g => g.Orders).Include(g => g.Orders.User).Where(o => (o.Orders.Invoice != null || o.Orders.Invoice != ""));
                var data = await applicationDbContext.ToListAsync();
                return View(data);
            }
            else
            {
                var orders = await _context.Orders
               .Where(o => o.IdentityUserId == curruser.Id && (o.Invoice != null || o.Invoice != "")).ToListAsync();

                if (orders == null)
                {
                    return View(NoContent());

                }

                List<GamesOrders>? list = new List<GamesOrders>();
                foreach(var order in orders)
                {
                    var gameOrder = await _context.GamesOrders.Include(g => g.Games).Include(g => g.Orders).Include(g => g.Orders.User)
                         .Where(go => go.OrdersId == order.Id).ToListAsync();

                    list.AddRange(gameOrder);
                }
                return View(list.OrderBy(o => o.OrdersId).ToList());

            }
        }

        [HttpGet, ActionName("ShowRechnung")]
        public async Task<IActionResult> ShowRechnung(int? id)
        {

            var order = await _context.Orders
             .FirstOrDefaultAsync(o => o.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            var gameOrder = await _context.GamesOrders.Include(g => g.Games).Include(g => g.Orders).Include(g => g.Orders.User)
               .Where(go => go.OrdersId == order.Id).ToListAsync();

            if (gameOrder.Count == 0)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = InvoiceDocumentDataSource.GetInvoiceDetails(order, gameOrder);
            var document = new InvoiceDocument(model);
            document.GeneratePdfAndShow();

            return RedirectToAction(nameof(Index));

        }
        // GET: History/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.GamesOrders == null)
            {
                return NotFound();
            }

            var gamesOrders = await _context.GamesOrders
                .Include(g => g.Games)
                .Include(g => g.Orders)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gamesOrders == null)
            {
                return NotFound();
            }

            return View(gamesOrders);
        }

        // GET: History/Create
        public IActionResult Create()
        {
            ViewData["GamesId"] = new SelectList(_context.Games, "Id", "Id");
            ViewData["OrdersId"] = new SelectList(_context.Orders, "Id", "Id");
            return View();
        }

        // POST: History/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Amount,GamesId,OrdersId")] GamesOrders gamesOrders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gamesOrders);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GamesId"] = new SelectList(_context.Games, "Id", "Id", gamesOrders.GamesId);
            ViewData["OrdersId"] = new SelectList(_context.Orders, "Id", "Id", gamesOrders.OrdersId);
            return View(gamesOrders);
        }

        // GET: History/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.GamesOrders == null)
            {
                return NotFound();
            }

            var gamesOrders = await _context.GamesOrders.FindAsync(id);
            if (gamesOrders == null)
            {
                return NotFound();
            }
            ViewData["GamesId"] = new SelectList(_context.Games, "Id", "Id", gamesOrders.GamesId);
            ViewData["OrdersId"] = new SelectList(_context.Orders, "Id", "Id", gamesOrders.OrdersId);
            return View(gamesOrders);
        }

        // POST: History/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Amount,GamesId,OrdersId")] GamesOrders gamesOrders)
        {
            if (id != gamesOrders.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gamesOrders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GamesOrdersExists(gamesOrders.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GamesId"] = new SelectList(_context.Games, "Id", "Id", gamesOrders.GamesId);
            ViewData["OrdersId"] = new SelectList(_context.Orders, "Id", "Id", gamesOrders.OrdersId);
            return View(gamesOrders);
        }

        // GET: History/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.GamesOrders == null)
            {
                return NotFound();
            }

            var gamesOrders = await _context.GamesOrders
                .Include(g => g.Games)
                .Include(g => g.Orders)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gamesOrders == null)
            {
                return NotFound();
            }

            return View(gamesOrders);
        }

        // POST: History/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.GamesOrders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.GamesOrders'  is null.");
            }
            var gamesOrders = await _context.GamesOrders.FindAsync(id);
            if (gamesOrders != null)
            {
                _context.GamesOrders.Remove(gamesOrders);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GamesOrdersExists(int id)
        {
          return (_context.GamesOrders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GamesForU/Views/History/Create.cshtml
@model GamesForU.Models.GamesOrders

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>GamesOrders</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GamesId" class="control-label"></label>
                <select asp-for="GamesId" class ="form-control" asp-items="ViewBag.GamesId"></select>
            </div>
            <div class="form-group">
                <label asp-for="OrdersId" class="control-label"></label>
                <select asp-for="OrdersId" class ="form-control" asp-items="ViewBag.OrdersId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GamesForU/Views/History/Delete.cshtml
@model GamesForU.Models.GamesOrders

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GamesOrders</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Games)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Games.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Orders)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Orders.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GamesForU/Views/History/Details.cshtml
@model GamesForU.Models.GamesOrders

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>GamesOrders</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Games)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Games.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Orders)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Orders.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GamesForU/Views/History/Edit.cshtml
@model GamesForU.Models.GamesOrders

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>GamesOrders</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GamesId" class="control-label"></label>
                <select asp-for="GamesId" class="form-control" asp-items="ViewBag.GamesId"></select>
                <span asp-validation-for="GamesId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrdersId" class="control-label"></label>
                <select asp-for="OrdersId" class="form-control" asp-items="ViewBag.OrdersId"></select>
                <span asp-validation-for="OrdersId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GamesForU/Views/History/Index.cshtml
@model IEnumerable<GamesForU.Models.GamesOrders>

@{
    ViewData["Title"] = "Index";
}

<h1> Mein Bestellverlauf</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Bestell ID
            </th>
            <th>
                Spiele
            </th>
            <th>
                Anzahl
            </th>
            <th>
                Preis
            </th>
            <th>
                Rechnung
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Orders.User.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            var list = Model.ToList();
            int tempOrder = list.First().OrdersId;
            long tempPrice = 0;
        }
        @foreach (var item in Model)
        {
            if (tempOrder != item.OrdersId)
            {

                <tr>
                    <td> GesPreis für Bestellung: @tempOrder: @tempPrice &euro;</td>
                </tr>
                tempOrder = item.OrdersId;

                tempPrice = 0;
            }
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrdersId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Games.Name)


                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)

                </td>
                <td>
                    @{
                        long pricefull = 0;
                        var price = Int64.Parse(item.Games.Price) * item.Amount;
                        pricefull += price;
                        tempPrice += pricefull;
                    }
                    @pricefull &euro;

                </td>
                <td>
                    @{
                        if (item.Orders.Invoice == null || item.Orders.Invoice == "")
                        {

                        }
                        else
                        {
                            <a asp-controller="History" asp-action="ShowRechnung" asp-route-id="@item.Orders.Id">@Html.DisplayFor(modelItem => item.Orders.Invoice)</a>

                        }

                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Orders.User.Email)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn" style="color:white; background-color: burlywood">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>