GamesForU/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GamesForU.Data;
using GamesForU.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace GamesForU.Controllers
{

    public class GamesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public GamesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }


        // GET: Games/Edit/5
        public async Task<IActionResult> AddToCard(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IdentityUser user = await GetCurrentUserAsync();

            if (user == null)
            {
                return NotFound();
            }

            var game = await _context.Games
                .Include(g => g.Pg)
                .Include(g => g.Publisher)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (game == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(o => o.IdentityUserId == user.Id && (o.Invoice == null || o.Invoice == ""));

            if (order == null)
            {
                order = new Orders
                {
                    IdentityUserId = user.Id,
                    Date = DateTime.Now,
                    Invoice = ""
                };

                _context.Add(order);
                await _context.SaveChangesAsync();
            }

            var gameOrder = await _context.GamesOrders
                .FirstOrDefaultAsync(go => go.GamesId == game.Id && go.OrdersId == order.Id);

            if (gameOrder == null)
            {
                gameOrder = new GamesOrders (1,game.Id,order.Id);
                _context.Add(gameOrder);
                await _context.SaveChangesAsync();
            }
            else
            {
                gameOrder.Amount++;
                _context.Update(gameOrder);
                await _context.SaveChangesAsync();
            }


            TempData["SuccessMessage"] = "Game " + game.Name + " was added to the shopping cart";
            return RedirectToAction(nameof(Index));
        }

        private Task<IdentityUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        // GET: Games
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParam"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["PriceSortParam"] = sortOrder == "Price" ? "price_desc" : "Price";
            ViewData["PublisherSortParam"] = sortOrder == "Publisher" ? "publisher_desc" : "Publisher";
            ViewData["CurrentFilter"] = searchString;

            var games = from g in _context.Games.Include(g => g.Pg).Include(g => g.Publisher)
                        select g;

            if (!String.IsNullOrEmpty(searchString))
            {
                games = games.Where(g => g.Name.Contains(searchString) || g.Publisher.Name.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    games = games.OrderByDescending(g => g.Name);
                    break;
                case "Price":
                    games = games.OrderBy(g => g.Price);
                    break;
                case "price_desc":
                    games = games.OrderByDescending(g => g.Price);
                    break;
                case "Publisher":
                    games = games.OrderBy(g => g.Publisher.Name);
                    break;
                case "publisher_desc":
                    games = games.OrderByDescending(g => g.Publisher.Name);
                    break;
                default:
                    games = games.OrderBy(g => g.Name);
                    break;
            }

            return View(await games.ToListAsync());
        }


        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Games == null)
            {
                return NotFound();
            }

            var games = await _context.Games
                .Include(g => g.Pg)
                .Include(g => g.Publisher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (games == null)
            {
                return NotFound();
            }

            return View(games);
        }
        [Authorize(Roles = "Admin")]

        // GET: Games/Create
        public IActionResult Create()
        {
            ViewData["PgId"] = new SelectList(_context.Pg, "Id", "AgeRestriction");
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "Id", "Name");
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Price,Amount,Name,PublisherId,PgId")] Games games)
        {
            if (ModelState.IsValid)
            {
                _context.Add(games);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PgId"] = new SelectList(_context.Pg, "Id", "AgeRestriction", games.PgId);
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "Id", "Name", games.PublisherId);
            return View(games);
        }
        [Authorize(Roles = "Admin")]

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Games == null)
            {
                return NotFound();
            }

            var games = await _context.Games.FindAsync(id);
            if (games == null)
            {
                return NotFound();
            }
            ViewData["PgId"] = new SelectList(_context.Pg, "Id", "AgeRestriction", games.PgId);
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "Id", "Name", games.PublisherId);
            return View(games);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Price,Amount,Name,PublisherId,PgId")] Games games)
        {
            if (id != games.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(games);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GamesExists(games.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PgId"] = new SelectList(_context.Pg, "Id", "AgeRestriction", games.PgId);
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "Id", "Name", games.PublisherId);
            return View(games);
        }
        [Authorize(Roles = "Admin")]

        // GET: Games/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Games == null)
            {
                return NotFound();
            }

            var games = await _context.Games
                .Include(g => g.Pg)
                .Include(g => g.Publisher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (games == null)
            {
                return NotFound();
            }

            return View(games);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Games == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Games'  is null.");
            }
            var games = await _context.Games.FindAsync(id);
            if (games != null)
            {
                _context.Games.Remove(games);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GamesExists(int id)
        {
          return (_context.Games?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GamesForU/Controllers/PgsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GamesForU.Data;
using GamesForU.Models;
using Microsoft.AspNetCore.Authorization;

namespace GamesForU.Controllers
{
    [Authorize(Roles = "Admin")]

    public class PgsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PgsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pgs
        public async Task<IActionResult> Index()
        {
              return _context.Pg != null ? 
                          View(await _context.Pg.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Pg'  is null.");
        }

        // GET: Pgs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pg == null)
            {
                return NotFound();
            }

            var pg = await _context.Pg
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pg == null)
            {
                return NotFound();
            }

            return View(pg);
        }

        // GET: Pgs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pgs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AgeRestriction")] Pg pg)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pg);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pg);
        }

        // GET: Pgs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pg == null)
            {
                return NotFound();
            }

            var pg = await _context.Pg.FindAsync(id);
            if (pg == null)
            {
                return NotFound();
            }
            return View(pg);
        }

        // POST: Pgs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AgeRestriction")] Pg pg)
        {
            if (id != pg.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pg);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PgExists(pg.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pg);
        }

        // GET: Pgs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pg == null)
            {
                return NotFound();
            }

            var pg = await _context.Pg
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pg == null)
            {
                return NotFound();
            }

            return View(pg);
        }

        // POST: Pgs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pg == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Pg'  is null.");
            }
            var pg = await _context.Pg.FindAsync(id);
            if (pg != null)
            {
                _context.Pg.Remove(pg);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PgExists(int id)
        {
          return (_context.Pg?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GamesForU/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GamesForU</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GamesForU.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GamesForU</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
              
                    <partial name="_MenuPartial" />

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GamesForU/Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav flex-grow-1">
    @if (!User.IsInRole("Admin"))
{
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index">Spiele</a>
            </li>
        @if (User.Identity.IsAuthenticated)
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="GamesOrders" asp-action="Index">Mein Warenkorb</a>
            </li>
      
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="History" asp-action="Index">Meine Bestellungen</a>
            </li>
        }
    }
else
{

        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index">Spiele</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Kategorien</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Pgs" asp-action="Index">PG</a>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Publishers" asp-action="Index">Publisher</a>
        </li>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="History" asp-action="Index">Alle Bestellungen</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="UserRoles" asp-action="Index">Benutzerverwaltung</a>
        </li>
}
   
</ul>